export const START_FETCHING = "START_FETCHING";
export const FETCHING_SUCCESS = "FETCHING_SUCCESS";
export const FETCHING_FAIL = "FETCHING_FAIL";
export const SET_ACTIVE_TASKS = "SET_ACTIVE_TASKS";
export const SET_SORTED_TASKS = "SET_SORTED_TASKS";
export const SET_COMPLETED_TASKS = "SET_COMPLETED_TASKS";
