export const FETCHING_SUCCESS = "FETCHING_SUCCESS";
export const SET_ACTIVE_TASKS = "SET_ACTIVE_TASKS";
export const SET_SORTED_TASKS = "SET_SORTED_TASKS";
export const SET_COMPLETED_TASKS = "SET_COMPLETED_TASKS";

export const SET_USER = "SET_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_ENTITY = "CLEAR_ENTITY";
export const CONFIRM_EMAIL = "CONFIRM_EMAIL";

export const LOGIN = "LOGIN";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const LOGOUT = "LOGOUT";
export const CONFIRM_EMAIL_SUCCESS = "CONFIRM_EMAIL_SUCCESS";

export const FETCHING_TASKS_SUCCESS = "FETCHING_TASKS_SUCCESS";
export const GET_SORTED_TASKS_SUCCESS = "GET_SORTED_TASKS_SUCCESS";
export const GET_COMPLETED_TASKS = "GET_COMPLETED_TASKS";
export const GET_ACTIVE_TASKS = "GET_ACTIVE_TASKS";
